Outline
This notebook demonstrates how to build a pipeline to predict results using Optuna hyperparameter lookup.

Preprocess and feature Engineering is base on previous notebook.

EDA link: [EDA of S6E3](https://www.kaggle.com/code/wesleyhuan/basic-eda-season-6-episode-3)

Key point: 
1. Data have a lot of non-numerical data in it. This requires to use OrdinalEncoder, OneHotEncoder and LabelEncoder depend on the data type.(Check out the link of **EDA of S6E3**)
2. This is a classification problem, but the submission we returned looks like this. This means we're trying to predict the probability of Churn. Therefore, you might need to use a different evaluation metric first, such as mean squared error (MSE) instead of the area under the curve (AUC).

Submission:

id,Churn

594194,0.1

594195,0.3

594196,0.2

etc.

Steps:

1. Load Data
2. Preprocess Data
3. Train model with Hyper parameter (OPTUNA)
4. Submission

# Load Data And Import Library

In [1]:
# import necessary library
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OrdinalEncoder,LabelEncoder
from sklearn.preprocessing import OneHotEncoder,StandardScaler

from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

#for optuna pipline
import optuna
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_val_score
from sklearn.base import BaseEstimator, TransformerMixin
import torch

#deal with gender ratio prolem 2026/02/28
from sklearn.model_selection import StratifiedKFold

In [2]:
# config
class CFG:
    train_csv = '/kaggle/input/competitions/playground-series-s6e3/train.csv'
    test_csv = '/kaggle/input/competitions/playground-series-s6e3/test.csv'
    sample_submission_csv = '/kaggle/input/competitions/playground-series-s6e3/sample_submission.csv'
    N_FOLDS = 5
    RANDOM_SEED = 42
    
#torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
train = pd.read_csv(CFG.train_csv)
test = pd.read_csv(CFG.test_csv)

In [4]:
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [5]:
test.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65

# Preprocess Data

In [6]:
class Preprocessor:
    def __init__(self):
        self.medians = {}
        self.scaler = StandardScaler()
        self.one_hot_encoder = None
        
        self.binary_cols = ['gender', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']
        self.replace_cols = ['MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 
                             'TechSupport', 'StreamingTV', 'StreamingMovies']
        self.contract_mapping = {'Month-to-month': 0, 'One year': 1, 'Two year': 2}
        self.ohe_cols = ['InternetService', 'PaymentMethod']
        self.numeric_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

    def create_interaction_features(self, df):
        df = df.copy()
        
        if 'TotalCharges' in df.columns:
            df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
        
        if 'MonthlyCharges' in df.columns and 'TotalCharges' in df.columns:
            df['Monthly_Fee_Ratio'] = df['MonthlyCharges'] / (df['TotalCharges'] + 1e-6)
        return df

    def fit(self, df, y=None):
        df_tmp = self.create_interaction_features(df)
        
        # learn median value
        curr_num_cols = df_tmp.select_dtypes(include=[np.number]).columns.tolist()
        for col in curr_num_cols:
            self.medians[col] = df_tmp[col].median()
            
        # fit OneHotEncoder
        self.one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False, drop='first')
        self.one_hot_encoder.fit(df_tmp[self.ohe_cols].astype(str))
        
        return self

    def transform(self, df):
        df = df.copy()
        df = self.create_interaction_features(df)
        
        if 'id' in df.columns: df = df.drop(columns=['id'])
        
        # Binary Encoding
        for col in self.binary_cols:
            if col in df.columns:
                df[col] = df[col].apply(lambda x: 1 if x in ['Yes', 'Male'] else 0)

        # No internet service and No phone service to No
        for col in self.replace_cols:
            if col in df.columns:
                df[col] = df[col].replace({'No internet service': 'No', 'No phone service': 'No'})
                df[col] = df[col].apply(lambda x: 1 if x == 'Yes' else 0)

        # Ordinal Encoding
        if 'Contract' in df.columns:
            df['Contract'] = df['Contract'].map(self.contract_mapping).fillna(0).astype(int)

        # fill median into miss value
        for col, val in self.medians.items():
            if col in df.columns:
                df[col] = df[col].fillna(val)

        # One-Hot Encoding (InternetService, PaymentMethod)
        encoded_array = self.one_hot_encoder.transform(df[self.ohe_cols].astype(str))
        encoded_cols = self.one_hot_encoder.get_feature_names_out(self.ohe_cols)
        encoded_df = pd.DataFrame(encoded_array, columns=encoded_cols, index=df.index, dtype=int)
        
        df = pd.concat([df, encoded_df], axis=1)
        df = df.drop(columns=self.ohe_cols)
        
        if 'Churn' in df.columns and isinstance(df['Churn'].iloc[0], str):
            df['Churn'] = df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

        return df

In [7]:
preprocessor = Preprocessor()

train_raw = train
X_train_raw = train.drop(columns=['id'])
y_train = train['Churn']

# learn the rule (median value...)
preprocessor.fit(X_train_raw)

# preprocess data
X_train_processed = preprocessor.transform(X_train_raw)

In [8]:
X_train_processed.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,Monthly_Fee_Ratio,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,1,29,1,0,1,0,1,...,1,60.10,1653.85,0,0.036339,0,0,0,0,1
1,1,0,1,1,58,1,0,1,1,0,...,0,69.50,3778.20,0,0.018395,0,0,1,0,0
2,1,0,1,0,58,1,1,0,1,0,...,1,100.40,5841.35,0,0.017188,1,0,0,1,0
3,0,0,0,0,1,1,0,0,0,0,...,1,69.70,70.70,1,0.985856,1,0,0,1,0
4,0,0,0,0,1,1,0,0,0,0,...,1,70.45,70.45,1,1.000000,1,0,0,1,0

In [9]:
X_train_raw = train_raw.drop(columns=['Churn'])
y_train = X_train_processed['Churn']

# Train model with Hyper parameter (OPTUNA)

In [10]:
def XGB_objective(trial):
    model_params = {
        "n_estimators": trial.suggest_int("n_estimators", 300, 2000),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
    }
    model_params["scale_pos_weight"] = trial.suggest_float("scale_pos_weight", 1.0, 5.0)
    
    pipeline = Pipeline(
        steps=[
            ("preprocess", Preprocessor()),
            ("model", XGBRegressor(
                objective="reg:logistic",
                random_state=CFG.RANDOM_SEED,
                n_jobs=-1,
                **model_params
            ))
        ]
    )

    scores = cross_val_score(
        pipeline,
        X_train_raw,
        y_train,
        cv=CFG.N_FOLDS,
        scoring="neg_root_mean_squared_error",
        n_jobs=-1 
    )

    return -scores.mean()

In [11]:
study = optuna.create_study(direction="minimize")

# use Optuna to find best parameter
study.optimize(XGB_objective, n_trials=30)

[I 2026-03-24 14:20:56,532] A new study created in memory with name: no-name-eaf1baf1-33f0-422f-b4b8-2189881eb730
[I 2026-03-24 14:22:16,113] Trial 0 finished with value: 0.3819311082363129 and parameters: {'n_estimators': 789, 'max_depth': 3, 'learning_rate': 0.010571805507843484, 'subsample': 0.6142487256204707, 'colsample_bytree': 0.6954007810324208, 'min_child_weight': 3, 'reg_alpha': 0.37065890298075854, 'reg_lambda': 0.16551333579509017, 'scale_pos_weight': 4.991061903968921}. Best is trial 0 with value: 0.3819311082363129.
[I 2026-03-24 14:23:56,886] Trial 1 finished with value: 0.3651453971862793 and parameters: {'n_estimators': 663, 'max_depth': 8, 'learning_rate': 0.05838777420775207, 'subsample': 0.6294292157006185, 'colsample_bytree': 0.9062151112332641, 'min_child_weight': 2, 'reg_alpha': 0.03075111079167901, 'reg_lambda': 0.029138632550936034, 'scale_pos_weight': 4.659727116734095}. Best is trial 1 with value: 0.3651453971862793.
[I 2026-03-24 14:24:59,813] Trial 2 finished with value: 0.3483256995677948 and parameters: {'n_estimators': 501, 'max_depth': 5, 'learning_rate': 0.021831180219197173, 'subsample': 0.9850349572616774, 'colsample_bytree': 0.8828544242034035, 'min_child_weight': 2, 'reg_alpha': 1.4677088099535747e-07, 'reg_lambda': 9.862895926957692e-05, 'scale_pos_weight': 3.221038744026364}. Best is trial 2 with value: 0.3483256995677948.
[I 2026-03-24 14:26:48,252] Trial 3 finished with value: 0.32737911939620973 and parameters: {'n_estimators': 1531, 'max_depth': 3, 'learning_rate': 0.09912230838703204, 'subsample': 0.9310384125190976, 'colsample_bytree': 0.5463146351240322, 'min_child_weight': 8, 'reg_alpha': 4.2319291578085636e-05, 'reg_lambda': 2.204134776767419, 'scale_pos_weight': 2.259530361919575}. Best is trial 3 with value: 0.32737911939620973.
[I 2026-03-24 14:31:43,733] Trial 4 finished with value: 0.3107332170009613 and parameters: {'n_estimators': 1822, 'max_depth': 9, 'learning_rate': 0.012022980983357308, 'subsample': 0.7865730061581194, 'colsample_bytree': 0.6481183334729249, 'min_child_weight': 5, 'reg_alpha': 1.8766912811196453e-08, 'reg_lambda': 0.001236656318912963, 'scale_pos_weight': 1.3182995407660822}. Best is trial 4 with value: 0.3107332170009613.
[I 2026-03-24 14:33:58,833] Trial 5 finished with value: 0.36296674609184265 and parameters: {'n_estimators': 1177, 'max_depth': 6, 'learning_rate': 0.026011393526155367, 'subsample': 0.6663009445146084, 'colsample_bytree': 0.5848846870581578, 'min_child_weight': 7, 'reg_alpha': 0.003096411914617403, 'reg_lambda': 4.0454698414625005e-05, 'scale_pos_weight': 4.231327420326}. Best is trial 4 with value: 0.3107332170009613.
[I 2026-03-24 14:38:32,841] Trial 6 finished with value: 0.3263712704181671 and parameters: {'n_estimators': 1467, 'max_depth': 10, 'learning_rate': 0.012336336762510976, 'subsample': 0.9669782336010039, 'colsample_bytree': 0.5052468433226833, 'min_child_weight': 4, 'reg_alpha': 1.565084693177303e-06, 'reg_lambda': 0.000522284890986686, 'scale_pos_weight': 2.2847849716854243}. Best is trial 4 with value: 0.3107332170009613.
[I 2026-03-24 14:42:32,636] Trial 7 finished with value: 0.36575551629066466 and parameters: {'n_estimators': 1744, 'max_depth': 8, 'learning_rate': 0.07819111561578868, 'subsample': 0.57733430480383, 'colsample_bytree': 0.7715029960689245, 'min_child_weight': 7, 'reg_alpha': 2.4198576811756835e-08, 'reg_lambda': 0.0026630289180074643, 'scale_pos_weight': 4.957303178466772}. Best is trial 4 with value: 0.3107332170009613.
[I 2026-03-24 14:43:59,192] Trial 8 finished with value: 0.3599343180656433 and parameters: {'n_estimators': 849, 'max_depth': 5, 'learning_rate': 0.1474551521624076, 'subsample': 0.5307888081609318, 'colsample_bytree': 0.7417061536827505, 'min_child_weight': 9, 'reg_alpha': 1.3101406662255921e-05, 'reg_lambda': 4.1443858799220774e-08, 'scale_pos_weight': 4.0305865208572556}. Best is trial 4 with value: 0.3107332170009613.
[I 2026-03-24 14:45:33,195] Trial 9 finished with value: 0.3612876236438751 and parameters: {'n_estimators': 555, 'max_depth': 8, 'learning_rate': 0.015810360435258155, 'subsample': 0.9928670865469681, 'colsample_bytree': 0.6829422302283057, 'min_child_weight': 1, 'reg_alpha': 4.354601931126229e-07, 'reg_lambda': 0.39251647548442825, 'scale_pos_weight': 4.090433103057544}. Best is trial 4 with value: 0.3107332170009613.
[I 2026-03-24 14:50:23,564] Trial 10 finished with value: 0.31352282762527467 and parameters: {'n_estimators': 1941, 'max_depth': 10, 'learning_rate': 0.04120587283652507, 'subsample': 0.8198802099492021, 'colsample_bytree': 0.9945937588229159, 'min_child_weight': 5, 'reg_alpha': 0.0004312227659228518, 'reg_lambda': 6.980747594957215e-07, 'scale_pos_weight': 1.12078386374259}. Best is trial 4 with value: 0.3107332170009613.
[I 2026-03-24 14:55:15,302] Trial 11 finished with value: 0.31123220920562744 and parameters: {'n_estimators': 1949, 'max_depth': 10, 'learning_rate': 0.0275473428231411, 'subsample': 0.8230813006683739, 'colsample_bytree': 0.967885845972095, 'min_child_weight': 5, 'reg_alpha': 0.0007963166788265364, 'reg_lambda': 4.981685707214169e-07, 'scale_pos_weight': 1.0377648767792647}. Best is trial 4 with value: 0.3107332170009613.
[I 2026-03-24 15:00:46,193] Trial 12 finished with value: 0.3103052258491516 and parameters: {'n_estimators': 1991, 'max_depth': 9, 'learning_rate': 0.032286257813730304, 'subsample': 0.7956900692733789, 'colsample_bytree': 0.6136057903455179, 'min_child_weight': 5, 'reg_alpha': 9.53134737479587, 'reg_lambda': 1.2050073367118628e-06, 'scale_pos_weight': 1.1814698667340033}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:05:15,305] Trial 13 finished with value: 0.31795257329940796 and parameters: {'n_estimators': 1632, 'max_depth': 9, 'learning_rate': 0.03333712387985033, 'subsample': 0.7498587426973669, 'colsample_bytree': 0.6200498404915511, 'min_child_weight': 6, 'reg_alpha': 5.655263224557294, 'reg_lambda': 7.593718502103776e-06, 'scale_pos_weight': 1.7429994693641402}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:07:46,054] Trial 14 finished with value: 0.3160363495349884 and parameters: {'n_estimators': 1164, 'max_depth': 7, 'learning_rate': 0.01806796751594255, 'subsample': 0.7304773355673224, 'colsample_bytree': 0.6327752705840582, 'min_child_weight': 4, 'reg_alpha': 8.291640158476998, 'reg_lambda': 0.0032174276911769908, 'scale_pos_weight': 1.677356019542672}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:10:48,434] Trial 15 finished with value: 0.3370869576931 and parameters: {'n_estimators': 1370, 'max_depth': 9, 'learning_rate': 0.04506073844480427, 'subsample': 0.8647538895160031, 'colsample_bytree': 0.7983323091069349, 'min_child_weight': 6, 'reg_alpha': 0.04805723979864493, 'reg_lambda': 2.2869535293004654e-08, 'scale_pos_weight': 2.906130347410535}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:14:23,619] Trial 16 finished with value: 0.3152369260787964 and parameters: {'n_estimators': 1787, 'max_depth': 7, 'learning_rate': 0.01596515633072058, 'subsample': 0.7002530260100562, 'colsample_bytree': 0.679874667587564, 'min_child_weight': 4, 'reg_alpha': 1.6065412835383995e-08, 'reg_lambda': 3.954930540366129e-06, 'scale_pos_weight': 1.6364776715418448}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:19:20,438] Trial 17 finished with value: 0.3275592863559723 and parameters: {'n_estimators': 1968, 'max_depth': 9, 'learning_rate': 0.010454394205723236, 'subsample': 0.8162318361255668, 'colsample_bytree': 0.5786132077879875, 'min_child_weight': 9, 'reg_alpha': 1.4951220167588486e-05, 'reg_lambda': 0.0012275838717643384, 'scale_pos_weight': 2.3229770724515775}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:21:28,230] Trial 18 finished with value: 0.3407552182674408 and parameters: {'n_estimators': 1353, 'max_depth': 6, 'learning_rate': 0.05806804380667143, 'subsample': 0.889884724992507, 'colsample_bytree': 0.8195475818404487, 'min_child_weight': 10, 'reg_alpha': 0.5863862538056791, 'reg_lambda': 0.013787864984765546, 'scale_pos_weight': 2.9997511403923096}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:25:48,276] Trial 19 finished with value: 0.3247626483440399 and parameters: {'n_estimators': 1769, 'max_depth': 9, 'learning_rate': 0.17662680774721387, 'subsample': 0.7773437384405707, 'colsample_bytree': 0.5012545414796125, 'min_child_weight': 7, 'reg_alpha': 0.0048872234534711205, 'reg_lambda': 5.301921119173526e-05, 'scale_pos_weight': 1.37272372092481}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:26:44,137] Trial 20 finished with value: 0.3506781220436096 and parameters: {'n_estimators': 339, 'max_depth': 8, 'learning_rate': 0.03401189883586512, 'subsample': 0.8919010200661238, 'colsample_bytree': 0.650477736495622, 'min_child_weight': 3, 'reg_alpha': 5.290559178932282e-05, 'reg_lambda': 9.792098009978144e-07, 'scale_pos_weight': 3.5098058772642124}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:31:35,656] Trial 21 finished with value: 0.3110978364944458 and parameters: {'n_estimators': 1994, 'max_depth': 10, 'learning_rate': 0.025275869647145253, 'subsample': 0.8075886376347897, 'colsample_bytree': 0.9790355069857225, 'min_child_weight': 5, 'reg_alpha': 0.0010717927354677965, 'reg_lambda': 2.3312667105009392e-07, 'scale_pos_weight': 1.0311959462699978}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:36:33,268] Trial 22 finished with value: 0.3211576402187347 and parameters: {'n_estimators': 1849, 'max_depth': 10, 'learning_rate': 0.02120162937102616, 'subsample': 0.7746814418309493, 'colsample_bytree': 0.7382160559572731, 'min_child_weight': 5, 'reg_alpha': 0.43069761144680097, 'reg_lambda': 1.2265481616391652e-07, 'scale_pos_weight': 1.9508658575634183}. Best is trial 12 with value: 0.3103052258491516.
/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
[I 2026-03-24 15:40:25,824] Trial 23 finished with value: 0.31212868094444274 and parameters: {'n_estimators': 1640, 'max_depth': 9, 'learning_rate': 0.0264369251908067, 'subsample': 0.7086893921148651, 'colsample_bytree': 0.8813506831349087, 'min_child_weight': 6, 'reg_alpha': 2.572698817521767e-06, 'reg_lambda': 3.4268025117671224e-06, 'scale_pos_weight': 1.3469775422076142}. Best is trial 12 with value: 0.3103052258491516.
[I 2026-03-24 15:45:41,723] Trial 24 finished with value: 0.3092066466808319 and parameters: {'n_estimators': 1988, 'max_depth': 10, 'learning_rate': 0.013411385315033839, 'subsample': 0.8485239798057462, 'colsample_bytree': 0.5901134524372337, 'min_child_weight': 4, 'reg_alpha': 0.04276822772612425, 'reg_lambda': 1.0899002466658363e-08, 'scale_pos_weight': 1.0066898968965003}. Best is trial 24 with value: 0.3092066466808319.
[I 2026-03-24 15:49:50,325] Trial 25 finished with value: 0.3118430256843567 and parameters: {'n_estimators': 1674, 'max_depth': 9, 'learning_rate': 0.013649505164343354, 'subsample': 0.8598705118129941, 'colsample_bytree': 0.5781021852215312, 'min_child_weight': 3, 'reg_alpha': 0.03683546732656726, 'reg_lambda': 1.3889593910922745e-08, 'scale_pos_weight': 1.4058759498326228}. Best is trial 24 with value: 0.3092066466808319.
[I 2026-03-24 15:53:20,384] Trial 26 finished with value: 0.3331762313842773 and parameters: {'n_estimators': 1845, 'max_depth': 7, 'learning_rate': 0.012954369943263697, 'subsample': 0.9202135213779546, 'colsample_bytree': 0.5432215357283072, 'min_child_weight': 4, 'reg_alpha': 3.6620060346769843, 'reg_lambda': 1.0062804842537116e-08, 'scale_pos_weight': 2.5819031695545185}. Best is trial 24 with value: 0.3092066466808319.
[I 2026-03-24 15:56:44,730] Trial 27 finished with value: 0.3221812903881073 and parameters: {'n_estimators': 1543, 'max_depth': 8, 'learning_rate': 0.018705798981052072, 'subsample': 0.778375291499228, 'colsample_bytree': 0.6221886370576314, 'min_child_weight': 2, 'reg_alpha': 0.14292888046698538, 'reg_lambda': 2.0149586257310418e-05, 'scale_pos_weight': 2.0356370630569556}. Best is trial 24 with value: 0.3092066466808319.
[I 2026-03-24 16:01:46,658] Trial 28 finished with value: 0.31149030327796934 and parameters: {'n_estimators': 1849, 'max_depth': 10, 'learning_rate': 0.010277733189065968, 'subsample': 0.8620424189979881, 'colsample_bytree': 0.7039628178157902, 'min_child_weight': 6, 'reg_alpha': 0.008027224528579855, 'reg_lambda': 0.00016672378976189084, 'scale_pos_weight': 1.3614443757483752}. Best is trial 24 with value: 0.3092066466808319.
[I 2026-03-24 16:03:14,048] Trial 29 finished with value: 0.3212317943572998 and parameters: {'n_estimators': 903, 'max_depth': 4, 'learning_rate': 0.014692841455311847, 'subsample': 0.66413922346508, 'colsample_bytree': 0.656435483561529, 'min_child_weight': 3, 'reg_alpha': 0.8813256781420974, 'reg_lambda': 5.866789302376234e-08, 'scale_pos_weight': 1.8402243346298446}. Best is trial 24 with value: 0.3092066466808319.

In [12]:
print(f"Best AUC score: {study.best_value:.4f}")
print("Best parameters:", study.best_params)

Best AUC score: 0.3092
Best parameters: {'n_estimators': 1988, 'max_depth': 10, 'learning_rate': 0.013411385315033839, 'subsample': 0.8485239798057462, 'colsample_bytree': 0.5901134524372337, 'min_child_weight': 4, 'reg_alpha': 0.04276822772612425, 'reg_lambda': 1.0899002466658363e-08, 'scale_pos_weight': 1.0066898968965003}

# Submission

In [13]:
final_pipeline = Pipeline(
    steps=[
        ("preprocess", Preprocessor()),
        ("model", XGBRegressor(
            **study.best_params,
            objective="reg:logistic",
            random_state=CFG.RANDOM_SEED,
            n_jobs=-1
        ))
    ]
)

final_pipeline.fit(X_train_raw, y_train)
test_id = test["id"]
test = test.drop(columns=['id'])
y_pred = final_pipeline.predict(test)

In [14]:
submission = pd.read_csv(CFG.sample_submission_csv)

submission = pd.DataFrame({
    'id': test_id, 
    'Churn': y_pred   
})

submission.to_csv('submission.csv', index=False)

In [15]:
submission.head()

       id     Churn
0  594194  0.098712
1  594195  0.000254
2  594196  0.116532
3  594197  0.001704
4  594198  0.474446