# Outline

This notebook demonstrates how to build a pipeline to predict results using Optuna hyperparameter lookup.

Preprocess and feature Engineering is base on previous notebook.

EDA link: [EDA of S6E2](https://www.kaggle.com/code/wesleyhuan/basic-eda-season-6-episode-2)

**Key point: This is a classification problem, but the submission we returned looks like this. This means we're trying to predict the probability of heart disease. Therefore, you might need to use a different evaluation metric, such as mean squared error (MSE) instead of the area under the curve (AUC).**

Submission:

id,Heart Disease

630000,0.2

630001,0.3

630002,0.1

etc.

Steps:

1. Load Data
2. Preprocess Data
3. Train model with Hyper parameter (OPTUNA)
4. Submission

In [1]:
# import necessary library
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder,StandardScaler

from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

#for optuna pipline
import optuna
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_val_score
from sklearn.base import BaseEstimator, TransformerMixin
import torch

In [2]:
# config
class CFG:
    train_csv = '/kaggle/input/playground-series-s6e2/train.csv'
    test_csv = '/kaggle/input/playground-series-s6e2/test.csv'
    sample_submission_csv = '/kaggle/input/playground-series-s6e2/sample_submission.csv'
    N_FOLDS = 5
    RANDOM_SEED = 42
    
#torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Load Data

In [3]:
train = pd.read_csv(CFG.train_csv)
test = pd.read_csv(CFG.test_csv)

In [4]:
train.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [5]:
test.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,630000,58,1,3,120,288,0,2,145,1,0.8,2,3,3
1,630001,55,0,2,120,209,0,0,172,0,0.0,1,0,3
2,630002,54,1,4,120,268,0,0,150,1,0.0,2,3,7
3,630003,44,0,3,112,177,0,0,168,0,0.9,1,0,3
4,630004,43,1,1,138,267,0,0,163,0,1.8,2,0,7

# Preprocess Data

In [6]:
class Preprocessor:
    def __init__(self):
        self.medians = {}
        self.encoders = {}
        self.numeric_cols = []
        self.all_non_numeric = []
        self.scaler = StandardScaler() # initial std scaler
        self.scaling_cols = ['Age', 'BP', 'Cholesterol', 'Max HR', 'ST depression', 'BP_Age_Product']
        self.categorical_cols = ['Chest pain type', 'Thallium', 'Slope of ST', 'EKG results']
        self.level_mapping = {'Absence': 0, 'Presence': 1}
        self.level_cols = ['Heart Disease']

        
    def create_interaction_features(self, df):# add because of the Correlation matrix
        df = df.copy()
        
        # Age * BP
        if 'Age' in df.columns and 'BP' in df.columns:
            df['BP_Age_Product'] = df['Age'] * df['BP']
        
        return df
        
    def fit(self, df, y=None):
        """
        Learn the parameters (medians, categories) from the TRAINING data.
        """
        ##############df_temp = self.create_interaction_features(df)
        # Identify columns
        self.numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        
        # Learn Medians for numeric columns
        for col in self.numeric_cols:
            self.medians[col] = df[col].median()
            
        # One hot encode the faeture 
        self.one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
        self.one_hot_encoder.fit(df[self.categorical_cols].astype(str))

        # StandardScaler
        existing_scaling_cols = [c for c in self.scaling_cols if c in df.columns]
        if existing_scaling_cols:
            self.scaler.fit(df[existing_scaling_cols].fillna(self.medians))
            
        return self

    def transform(self, df):
        """
        Apply the learned parameters to the data (Train or Test).
        """
        df = df.copy()

        #############df = self.create_interaction_features(df)
        # Drop irrelevant columns (ID is usually dropped, Target handled separately)
        # Note: We don't drop target here to keep X and y aligned until the end
        if 'id' in df.columns:
            df = df.drop(columns=['id'])

        # level encoding for heart disease
        for col in self.level_cols:
            if col in df.columns:
                if not np.issubdtype(df[col].dtype, np.number):
                    df[col] = df[col].map(self.level_mapping).fillna(0).astype(int)
                else:
                    df[col] = df[col].fillna(0).astype(int)
        # Impute Missing Values using LEARNED medians
        for col in self.numeric_cols:
            if col in df.columns:
                df[col] = df[col].fillna(self.medians.get(col, 0))

        # Get one hot encode feature
        encoded_array = self.one_hot_encoder.transform(df[self.categorical_cols].astype(str))
        encoded_cols = self.one_hot_encoder.get_feature_names_out(self.categorical_cols)
        encoded_df = pd.DataFrame(encoded_array, columns=encoded_cols, index=df.index)
        
        # concat into original df
        df = pd.concat([df, encoded_df], axis=1)
        df = df.drop(columns=self.categorical_cols)

        # StandardScaler
        # make sure Age, BP feature is Standardlize
        target_scaling = [c for c in self.scaling_cols if c in df.columns]
        if target_scaling:
            df[target_scaling] = self.scaler.transform(df[target_scaling])
            
        return df

In [7]:
preprocessor = Preprocessor()

train_raw = train.drop(columns=['id'])

# learn the rule (median value...)
preprocessor.fit(train_raw)

# preprocess data
X_train_processed = preprocessor.transform(train_raw)

In [8]:
X_train_processed.head()

,Age,Sex,BP,Cholesterol,FBS over 120,Max HR,Exercise angina,ST depression,Number of vessels fluro,Heart Disease,...,Chest pain type_4,Thallium_3,Thallium_6,Thallium_7,Slope of ST_1,Slope of ST_2,Slope of ST_3,EKG results_0,EKG results_1,EKG results_2
0,0.467921,1,1.435822,-0.178490,0,0.271190,1,3.040655,2,1,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1,-0.258797,1,-0.367088,2.374837,0,0.951359,0,-0.754928,0,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.225682,0,1.970017,-1.692672,0,-0.095054,0,-0.754928,0,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,-1.227755,0,0.233882,-0.475388,0,-0.147375,0,0.299400,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.467921,1,0.634529,-0.326939,0,-1.455391,1,3.251520,3,1,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [9]:
X_train_raw = train_raw.drop(columns=['Heart Disease'])
y_train = X_train_processed['Heart Disease']

# Train model with Hyper parameter (OPTUNA)

In [10]:
def XGB_objective(trial):
    model_params = {
        "n_estimators": trial.suggest_int("n_estimators", 300, 2000),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
    }
    
    pipeline = Pipeline(
        steps=[
            ("preprocess", Preprocessor()),
            ("model", XGBRegressor(
                objective="reg:logistic",
                random_state=CFG.RANDOM_SEED,
                n_jobs=-1,
                **model_params
            ))
        ]
    )

    scores = cross_val_score(
        pipeline,
        X_train_raw,
        y_train,
        cv=CFG.N_FOLDS,
        scoring="neg_root_mean_squared_error", # 改用 RMSE (負值是為了讓 Optuna 最大化)
        n_jobs=-1 
    )

    return -scores.mean()

In [11]:
study = optuna.create_study(direction="minimize")

# use Optuna to find best parameter
study.optimize(XGB_objective, n_trials=30)

[I 2026-02-10 15:53:52,568] A new study created in memory with name: no-name-736797e1-b266-465b-b53c-4cfdcda6e66a
[I 2026-02-10 15:55:39,290] Trial 0 finished with value: 0.2863613963127136 and parameters: {'n_estimators': 308, 'max_depth': 9, 'learning_rate': 0.016490809073873867, 'subsample': 0.5820466091273466, 'colsample_bytree': 0.6353249214632788, 'min_child_weight': 9, 'reg_alpha': 0.0006445229341647551, 'reg_lambda': 0.00026536012394400054}. Best is trial 0 with value: 0.2863613963127136.
[I 2026-02-10 16:02:05,826] Trial 1 finished with value: 0.28575687408447265 and parameters: {'n_estimators': 1600, 'max_depth': 9, 'learning_rate': 0.011229595127598802, 'subsample': 0.9353968263466055, 'colsample_bytree': 0.843707795294952, 'min_child_weight': 3, 'reg_alpha': 1.3982279159188722e-08, 'reg_lambda': 1.1667927911108464}. Best is trial 1 with value: 0.28575687408447265.
[I 2026-02-10 16:05:39,417] Trial 2 finished with value: 0.285772967338562 and parameters: {'n_estimators': 1306, 'max_depth': 5, 'learning_rate': 0.01038343228934768, 'subsample': 0.9000147743784246, 'colsample_bytree': 0.9566539583703746, 'min_child_weight': 6, 'reg_alpha': 3.149909333574602e-06, 'reg_lambda': 0.00012196844890791652}. Best is trial 1 with value: 0.28575687408447265.
[I 2026-02-10 16:08:16,419] Trial 3 finished with value: 0.28528451919555664 and parameters: {'n_estimators': 833, 'max_depth': 6, 'learning_rate': 0.01926594363436114, 'subsample': 0.5691742010287306, 'colsample_bytree': 0.9450939923565855, 'min_child_weight': 4, 'reg_alpha': 0.001731213190157338, 'reg_lambda': 0.004500848850869248}. Best is trial 3 with value: 0.28528451919555664.
[I 2026-02-10 16:11:04,290] Trial 4 finished with value: 0.2871055781841278 and parameters: {'n_estimators': 782, 'max_depth': 9, 'learning_rate': 0.05643822657649225, 'subsample': 0.906553837720171, 'colsample_bytree': 0.8545805161456961, 'min_child_weight': 9, 'reg_alpha': 2.704238940701167e-06, 'reg_lambda': 0.06641200570249162}. Best is trial 3 with value: 0.28528451919555664.
[I 2026-02-10 16:12:37,132] Trial 5 finished with value: 0.28679741024971006 and parameters: {'n_estimators': 329, 'max_depth': 10, 'learning_rate': 0.06129620942666488, 'subsample': 0.8549983936740065, 'colsample_bytree': 0.8975523405930803, 'min_child_weight': 6, 'reg_alpha': 1.3620004845823715e-06, 'reg_lambda': 9.026790108552868e-06}. Best is trial 3 with value: 0.28528451919555664.
[I 2026-02-10 16:16:16,384] Trial 6 finished with value: 0.2853386580944061 and parameters: {'n_estimators': 1057, 'max_depth': 7, 'learning_rate': 0.015032306120669525, 'subsample': 0.6481390060346921, 'colsample_bytree': 0.957155334012752, 'min_child_weight': 5, 'reg_alpha': 0.21664291081147258, 'reg_lambda': 0.008658010685947204}. Best is trial 3 with value: 0.28528451919555664.
[I 2026-02-10 16:18:31,464] Trial 7 finished with value: 0.2851791143417358 and parameters: {'n_estimators': 764, 'max_depth': 6, 'learning_rate': 0.07653336337099237, 'subsample': 0.7608539355142347, 'colsample_bytree': 0.5000269528431769, 'min_child_weight': 6, 'reg_alpha': 4.635605994847038, 'reg_lambda': 5.8520409383866395e-05}. Best is trial 7 with value: 0.2851791143417358.
[I 2026-02-10 16:22:42,067] Trial 8 finished with value: 0.2879382371902466 and parameters: {'n_estimators': 1442, 'max_depth': 7, 'learning_rate': 0.09385792648014052, 'subsample': 0.87594035743802, 'colsample_bytree': 0.7718719517954507, 'min_child_weight': 4, 'reg_alpha': 0.00015663126773782804, 'reg_lambda': 6.846364011765202}. Best is trial 7 with value: 0.2851791143417358.
[I 2026-02-10 16:27:06,814] Trial 9 finished with value: 0.28559447526931764 and parameters: {'n_estimators': 957, 'max_depth': 9, 'learning_rate': 0.010008119786182788, 'subsample': 0.6184360092138808, 'colsample_bytree': 0.7545811381280969, 'min_child_weight': 10, 'reg_alpha': 1.3100296867253719e-05, 'reg_lambda': 0.00015431165580546226}. Best is trial 7 with value: 0.2851791143417358.
[I 2026-02-10 16:28:21,125] Trial 10 finished with value: 0.28475694060325624 and parameters: {'n_estimators': 623, 'max_depth': 3, 'learning_rate': 0.18492471912534444, 'subsample': 0.7592777307855054, 'colsample_bytree': 0.5210562961307208, 'min_child_weight': 2, 'reg_alpha': 5.1363389376332105, 'reg_lambda': 1.1572519458030572e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:29:36,164] Trial 11 finished with value: 0.2847749650478363 and parameters: {'n_estimators': 611, 'max_depth': 3, 'learning_rate': 0.15460388698430003, 'subsample': 0.7416496524907175, 'colsample_bytree': 0.5012711874509878, 'min_child_weight': 1, 'reg_alpha': 6.606566215744261, 'reg_lambda': 2.2900970050592217e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:33:09,567] Trial 12 finished with value: 0.2850577890872955 and parameters: {'n_estimators': 1946, 'max_depth': 3, 'learning_rate': 0.19627173388350339, 'subsample': 0.7623506450423663, 'colsample_bytree': 0.5077696078516722, 'min_child_weight': 1, 'reg_alpha': 3.638345760891999, 'reg_lambda': 1.1974677108392145e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:34:17,964] Trial 13 finished with value: 0.2849330544471741 and parameters: {'n_estimators': 572, 'max_depth': 3, 'learning_rate': 0.1988175566429956, 'subsample': 0.7081729025659219, 'colsample_bytree': 0.608084341068289, 'min_child_weight': 1, 'reg_alpha': 0.06567876708948613, 'reg_lambda': 1.1113635421336109e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:35:31,108] Trial 14 finished with value: 0.28493325114250184 and parameters: {'n_estimators': 551, 'max_depth': 4, 'learning_rate': 0.11841225228898676, 'subsample': 0.8113748707304637, 'colsample_bytree': 0.6065365579129794, 'min_child_weight': 2, 'reg_alpha': 0.052844008060710185, 'reg_lambda': 6.535754512135079e-07}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:36:52,230] Trial 15 finished with value: 0.28558954000473025 and parameters: {'n_estimators': 541, 'max_depth': 4, 'learning_rate': 0.03432370643930522, 'subsample': 0.7098943800729619, 'colsample_bytree': 0.5595858237661882, 'min_child_weight': 2, 'reg_alpha': 7.636169478726528, 'reg_lambda': 4.4858029221734454e-07}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:39:23,831] Trial 16 finished with value: 0.28550795912742616 and parameters: {'n_estimators': 1203, 'max_depth': 4, 'learning_rate': 0.1344881011193942, 'subsample': 0.675457809712786, 'colsample_bytree': 0.6845689897465048, 'min_child_weight': 2, 'reg_alpha': 0.42830736495611815, 'reg_lambda': 2.2530395698936152e-07}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:40:45,850] Trial 17 finished with value: 0.28597027659416197 and parameters: {'n_estimators': 625, 'max_depth': 3, 'learning_rate': 0.03154452670712043, 'subsample': 0.5087854499946695, 'colsample_bytree': 0.6871105903504939, 'min_child_weight': 1, 'reg_alpha': 0.008547744120201923, 'reg_lambda': 4.210074450815279e-06}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:42:52,723] Trial 18 finished with value: 0.28575509786605835 and parameters: {'n_estimators': 961, 'max_depth': 5, 'learning_rate': 0.14149916124419776, 'subsample': 0.9978884251945805, 'colsample_bytree': 0.5570140207693037, 'min_child_weight': 3, 'reg_alpha': 0.5664544961904644, 'reg_lambda': 8.01423353475082e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:43:52,902] Trial 19 finished with value: 0.2849814236164093 and parameters: {'n_estimators': 376, 'max_depth': 5, 'learning_rate': 0.10768051269302023, 'subsample': 0.8083369459402702, 'colsample_bytree': 0.5459557735628996, 'min_child_weight': 7, 'reg_alpha': 0.008057946098831068, 'reg_lambda': 5.148835070842154e-06}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:45:11,876] Trial 20 finished with value: 0.2847691297531128 and parameters: {'n_estimators': 701, 'max_depth': 3, 'learning_rate': 0.16353447738820806, 'subsample': 0.8034595915128134, 'colsample_bytree': 0.6799804644933205, 'min_child_weight': 3, 'reg_alpha': 1.3297908977888488, 'reg_lambda': 5.7496306366782616e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:46:30,925] Trial 21 finished with value: 0.2847659170627594 and parameters: {'n_estimators': 692, 'max_depth': 3, 'learning_rate': 0.15919023826474268, 'subsample': 0.7902591372265448, 'colsample_bytree': 0.6745539440798904, 'min_child_weight': 3, 'reg_alpha': 1.5141207606556146, 'reg_lambda': 3.160070203597152e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:48:05,254] Trial 22 finished with value: 0.28485737442970277 and parameters: {'n_estimators': 741, 'max_depth': 4, 'learning_rate': 0.08790802009202245, 'subsample': 0.8231015963580746, 'colsample_bytree': 0.6935083745064413, 'min_child_weight': 4, 'reg_alpha': 1.262019804130272, 'reg_lambda': 8.495199672080008e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:49:46,797] Trial 23 finished with value: 0.28493215441703795 and parameters: {'n_estimators': 937, 'max_depth': 3, 'learning_rate': 0.17335690115554026, 'subsample': 0.7875569097620009, 'colsample_bytree': 0.7174939680212955, 'min_child_weight': 3, 'reg_alpha': 0.08382512125655592, 'reg_lambda': 1.416445272734543e-06}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:50:48,856] Trial 24 finished with value: 0.28496173620223997 and parameters: {'n_estimators': 463, 'max_depth': 4, 'learning_rate': 0.12062124551906382, 'subsample': 0.8374704584113845, 'colsample_bytree': 0.7967436414811853, 'min_child_weight': 5, 'reg_alpha': 0.017784603257211255, 'reg_lambda': 3.886899240972897e-08}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:53:31,815] Trial 25 finished with value: 0.28670724034309386 and parameters: {'n_estimators': 1137, 'max_depth': 5, 'learning_rate': 0.1602511780323697, 'subsample': 0.7160697510938896, 'colsample_bytree': 0.6450386995176629, 'min_child_weight': 3, 'reg_alpha': 1.2076697886988779, 'reg_lambda': 2.0420107571532247e-07}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:54:48,766] Trial 26 finished with value: 0.2848630487918854 and parameters: {'n_estimators': 670, 'max_depth': 3, 'learning_rate': 0.07273436311523936, 'subsample': 0.7827548392823886, 'colsample_bytree': 0.6433282615030382, 'min_child_weight': 2, 'reg_alpha': 0.27178230954545657, 'reg_lambda': 2.0075278604252804e-05}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:55:56,091] Trial 27 finished with value: 0.2854795753955841 and parameters: {'n_estimators': 454, 'max_depth': 4, 'learning_rate': 0.043352129864352, 'subsample': 0.7339042082631031, 'colsample_bytree': 0.7311998954349013, 'min_child_weight': 4, 'reg_alpha': 1.5050190355578266, 'reg_lambda': 1.352891065325588e-06}. Best is trial 10 with value: 0.28475694060325624.
[I 2026-02-10 16:57:31,642] Trial 28 finished with value: 0.2847421705722809 and parameters: {'n_estimators': 853, 'max_depth': 3, 'learning_rate': 0.09743038309137159, 'subsample': 0.6739100939114254, 'colsample_bytree': 0.5885863384724501, 'min_child_weight': 3, 'reg_alpha': 6.734046383517411e-08, 'reg_lambda': 7.620094550071678e-08}. Best is trial 28 with value: 0.2847421705722809.
[I 2026-02-10 17:00:00,765] Trial 29 finished with value: 0.28620471358299254 and parameters: {'n_estimators': 904, 'max_depth': 6, 'learning_rate': 0.10151309571013471, 'subsample': 0.6727552632582297, 'colsample_bytree': 0.5939251955574418, 'min_child_weight': 7, 'reg_alpha': 1.9674893885210514e-08, 'reg_lambda': 1.1439007095558182e-08}. Best is trial 28 with value: 0.2847421705722809.

In [12]:
print(f"Best AUC score: {study.best_value:.4f}")
print("Best parameters:", study.best_params)

Best AUC score: 0.2847
Best parameters: {'n_estimators': 853, 'max_depth': 3, 'learning_rate': 0.09743038309137159, 'subsample': 0.6739100939114254, 'colsample_bytree': 0.5885863384724501, 'min_child_weight': 3, 'reg_alpha': 6.734046383517411e-08, 'reg_lambda': 7.620094550071678e-08}

# Submission

In [13]:
final_pipeline = Pipeline(
    steps=[
        ("preprocess", Preprocessor()),
        ("model", XGBRegressor(
            **study.best_params,
            objective="reg:logistic",
            random_state=CFG.RANDOM_SEED,
            n_jobs=-1
        ))
    ]
)

final_pipeline.fit(X_train_raw, y_train)
test_id = test["id"]
test = test.drop(columns=['id'])
y_pred = final_pipeline.predict(test)

In [14]:
submission = pd.read_csv(CFG.sample_submission_csv)

submission = pd.DataFrame({
    'id': test_id, 
    'Heart Disease': y_pred   
})

submission.to_csv('submission.csv', index=False)

In [15]:
submission.head()

       id  Heart Disease
0  630000       0.945953
1  630001       0.008409
2  630002       0.988815
3  630003       0.004417
4  630004       0.178509